upgrade jenkins version

diff --git a/Jenkin/jenkins-master/jenkins-support b/Jenkin/jenkins-master/jenkins-support
--- a/Jenkin/jenkins-master/jenkins-support
+++ b/Jenkin/jenkins-master/jenkins-support
@@ -1,5 +1,7 @@
 #!/bin/bash -eu
 
+: "${REF:="/usr/share/jenkins/ref"}"
+
 # compare if version1 < version2
 versionLT() {
     local v1; v1=$(echo "$1" | cut -d '-' -f 1 )
@@ -40,9 +42,9 @@ get_plugin_version() {
 copy_reference_file() {
     f="${1%/}"
     b="${f%.override}"
-    rel="${b:23}"
+    rel="${b#"$REF/"}"
     version_marker="${rel}.version_from_image"
-    dir=$(dirname "${b}")
+    dir=$(dirname "${rel}")
     local action;
     local reason;
     local container_version;
@@ -55,9 +57,15 @@ copy_reference_file() {
         if [[ -e $JENKINS_HOME/${version_marker} ]]; then
             marker_version=$(cat "$JENKINS_HOME/${version_marker}")
             if versionLT "$marker_version" "$container_version"; then
-                action="SKIPPED"
-                reason="Installed version ($container_version) has been manually upgraded from initial version ($marker_version)"
-                log=true
+                if ( versionLT "$container_version" "$image_version" && [[ -n $PLUGINS_FORCE_UPGRADE ]]); then
+                    action="UPGRADED"
+                    reason="Manually upgraded version ($container_version) is older than image version $image_version"
+                    log=true
+                else
+                    action="SKIPPED"
+                    reason="Installed version ($container_version) has been manually upgraded from initial version ($marker_version)"
+                    log=true
+                fi
             else
                 if [[ "$image_version" == "$container_version" ]]; then
                     action="SKIPPED"
@@ -97,7 +105,7 @@ copy_reference_file() {
         if [[ ! -e $JENKINS_HOME/${rel} || "$action" == "UPGRADED" || $f = *.override ]]; then
             action=${action:-"INSTALLED"}
             log=true
-            mkdir -p "$JENKINS_HOME/${dir:23}"
+            mkdir -p "$JENKINS_HOME/${dir}"
             cp -pr "${f}" "$JENKINS_HOME/${rel}";
             # pin plugins on initial copy
             touch "$JENKINS_HOME/${rel}.pinned"
@@ -111,8 +119,8 @@ copy_reference_file() {
         then
             action="INSTALLED"
             log=true
-            mkdir -p "$JENKINS_HOME/${dir:23}"
-            cp -pr "${f}" "$JENKINS_HOME/${rel}";
+            mkdir -p "$JENKINS_HOME/${dir}"
+            cp -pr "$(realpath "${f}")" "$JENKINS_HOME/${rel}";
         else
             action="SKIPPED"
         fi
@@ -132,7 +140,7 @@ copy_reference_file() {
 # timeout is given by TIMEOUT in seconds (default 1.)
 #
 function retry_command() {
-  local max_attempts=${ATTEMPTS-60}
+  local max_attempts=${ATTEMPTS-3}
   local timeout=${TIMEOUT-1}
   local success_timeout=${SUCCESS_TIMEOUT-1}
   local max_success_attempt=${SUCCESS_ATTEMPTS-1}
@@ -140,7 +148,7 @@ function retry_command() {
   local success_attempt=0
   local exitCode=0
 
-  while (( $attempt < $max_attempts ))
+  while (( attempt < max_attempts ))
   do
     set +e
     "$@"
@@ -150,17 +158,17 @@ function retry_command() {
     if [[ $exitCode == 0 ]]
     then
       success_attempt=$(( success_attempt + 1 ))
-      if (( $success_attempt >= $max_success_attempt))
+      if (( success_attempt >= max_success_attempt))
       then
         break
       else
-        sleep $success_timeout
+        sleep "$success_timeout"
         continue
       fi
     fi
 
     echo "$(date -u '+%T') Failure ($exitCode) Retrying in $timeout seconds..." 1>&2
-    sleep $timeout
+    sleep "$timeout"
     success_attempt=0
     attempt=$(( attempt + 1 ))
     timeout=$(( timeout ))
@@ -168,7 +176,7 @@ function retry_command() {
 
   if [[ $exitCode != 0 ]]
   then
-    echo "$(date -u '+%T') Failed in the last attempt ($@)" 1>&2
+    echo "$(date -u '+%T') Failed in the last attempt ($*)" 1>&2
   fi
 
   return $exitCode
